sudo: false
language: node_js
node_js:
  - 0.12
  - 4.2
  - stable
env:
  - ARANGODB_VERSION=2.6
  - ARANGODB_VERSION=2.7
  - ARANGODB_VERSION=2.8
before_install:
  - curl https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh | bash
after_script:
  - if [[ `node --version` == *v4.2* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
script:
  - npm run lint && npm run coverage
